### ISSUE TITLE
Add metadata for webservice clearly on website

### ISSUE THREAD

**Issue by DeniseSl22** [bridgedb/BridgeDbWebservice#14]
I think a nice new feature to have, is a link to an official release (e.g. from GitHub), the version of the webservice clearly depicted on the page (both webservice and main BridgeDb website), and a link to the docker image?

**Comment by egonw** [comment]
Okay, I don't remember the context of this one, sorry. Is this just about improving the BridgeDb website?

**Comment by DeniseSl22** [comment]
Both; for me it's now not clear which source code is used in the webservice.... If we add that information clearly on the main BridgeDb website, we can show to people that our code is updated frequently. The webservice itself has a "version" number (see printscreen) but is not (hyper)linked to the sourcecode.
![image](https://github.com/bridgedb/BridgeDbWebservice/assets/26277832/e57fa06a-62f9-468d-99bc-df365b7dbf9b)

I cannot find the version 1.0.1 in the source code repo either (https://github.com/bridgedb/swagger) ?
![image](https://github.com/bridgedb/BridgeDbWebservice/assets/26277832/16564d75-726e-4022-9af6-e0ebffc945e0)

Having this information available might also help us with debugging.

**Comment by egonw** [comment]
Thanks for the detail! I can work with this.

**Comment by egonw** [comment]
The proper version is now listed and I added a link to the source code.
