### ISSUE TITLE
Broken links on Swagger pages

### ISSUE THREAD

**Issue by Chris-Evelo** [bridgedb/BridgeDbWebservice#4]
Many, if not all, the links on Swagger pages like this one: https://bridgedb.github.io/swagger/#/Identifiers%20(Genes%2C%20proteins%2C%20metabolites%2C%20interactions)/get__organism__xrefs__systemCode___identifier_ that go to explanatory pages in vocabularies.bridgedb.org are broken.

**Comment by egonw** [comment]
I removed the link (in the new, upcoming interactive docs, see https://github.com/bridgedb/BridgeDbWebservice/pull/17).

In the future it can be added again, but not until we have a list of supported organisms on the BridgeDb website. For that, there is a plan to have that page and the page with system code autogenerated from the latest BridgeDb. But that has not been implemented yet.
